format = """
[░▒▓](#a3aed2)\
$os(bg:#a3aed2)\
$hostname\
[]()\
$directory\
[](fg:#769ff0)\
$git_branch\
$git_status\
$docker_context\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736)\
$time\
[ ](fg:#1d2230)\
\n$character"""

right_format = """
[](fg:#1d2230)\
[ ]()\
$localip\
[ ]()\
[](fg:#1d2230)"""

[character]
success_symbol = "[➜](bold fg:#769ff0)"
error_symbol = "[✗](bold fg:#ff6b6b)"

[localip]
ssh_only = false
format = '[󰩠 $localipv4](fg:#a0a9cb)'
disabled = false

[os]
disabled = false
format = "[$symbol]($style) "

[os.symbols]
Kali = "   "
Debian = "  "
Ubuntu = "  "
Linux = "  "
Windows = "  "

[hostname]
ssh_only = true
format = 'on [$hostname](bold yellow) '
trim_at = "."
disabled = false

[directory]
style = "fg:#b8c1d4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[ ](fg:#769ff0)[[ $symbol $branch ](fg:#769ff0)]($style)'

[git_status]
disabled = false
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)[](fg:#394260)]($style)'
ignore_submodules = true

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[python]
symbol = ""
style = ""
format = '[[ $symbol ($virtualenv) ](fg:#769ff0 )]($style)'

[nodejs]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0 )]($style)'

[rust]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0 )]($style)'

[golang]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0 )]($style)'

[php]
symbol = ""
style = ""
format = '[[ $symbol ($version) ](fg:#769ff0 )]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb)]($style)'
